// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkLoad;

#nullable disable

namespace WorkLoad.Migrations
{
    [DbContext(typeof(DbInter))]
    [Migration("20230623101758_addingrelatin")]
    partial class addingrelatin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("WorkLoad.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            firstName = "Pawel",
                            lastName = "Kownacki"
                        });
                });

            modelBuilder.Entity("WorkLoad.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("employeeID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("employeeID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Defekacja",
                            isDone = false,
                            priority = 5,
                            time = 1
                        });
                });

            modelBuilder.Entity("WorkLoad.Task", b =>
                {
                    b.HasOne("WorkLoad.Employee", "employee")
                        .WithMany("tasks")
                        .HasForeignKey("employeeID");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("WorkLoad.Employee", b =>
                {
                    b.Navigation("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
